//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        public int ID { get; set; }
        public string NO { get; set; }
        public string Category { get; set; }
        public string Belong { get; set; }
        public string EngineNo { get; set; }
        public string OriginalEmissionValues { get; set; }
        public string ProductModel { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string UserInfo { get; set; }
        public string IndividualCompany { get; set; }
        public string Telphone { get; set; }
        public Nullable<System.DateTime> Data_CreateTime { get; set; }
        public Nullable<System.DateTime> Data_LastChangeTime { get; set; }
        public string Color { get; set; }
        public string ModifiedCompany { get; set; }
        public string CarType { get; set; }
    }
}
