//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPService2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarNoProvince
    {
        public int ID { get; set; }
        public string NO { get; set; }
        public string CarNo { get; set; }
        public string Province { get; set; }
    }
}
