//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tail.Gas.Detection.Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarNoBlong
    {
        public int ID { get; set; }
        public string NO { get; set; }
        public string Belong { get; set; }
        public string CarNo { get; set; }
    }
}
