//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tail.Gas.Detection.Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleInfo
    {
        public int id { get; set; }
        public string rolename { get; set; }
        public string page { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> lasttime { get; set; }
    }
}
